version: '3'

services:
  ppa:
    container_name: penguins-eggs-ppa
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./..:/usr/share/nginx/html
      - ./nginx.app.conf:/etc/nginx/conf.d/default.conf